{{- range $collector, $schedule := .Values.collector.schedules }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: asylguiden-collector-{{ $collector }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "asylguiden.labels" $ | nindent 4 }}
    app.kubernetes.io/name: collector
    app.kubernetes.io/component: {{ $collector }}
spec:
  schedule: {{ $schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "asylguiden.selectorLabels" "collector" | nindent 12 }}
            app.kubernetes.io/component: {{ $collector }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: collector
              image: "{{ $.Values.collector.image.repository }}:{{ $.Values.collector.image.tag }}"
              imagePullPolicy: {{ $.Values.collector.image.pullPolicy }}
              args: ["--once", "--collector={{ $collector }}"]
              env:
                - name: STRAPI_URL
                  value: "http://asylguiden-backend:1337"
                - name: LOG_LEVEL
                  value: {{ $.Values.collector.logLevel | quote }}
                - name: STRAPI_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: asylguiden-secret
                      key: COLLECTOR_STRAPI_API_TOKEN
{{- end }}
