apiVersion: v1
kind: Service
metadata:
  name: asylguiden-postgres
  labels:
    {{- include "asylguiden.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "asylguiden.selectorLabels" "postgres" | nindent 4 }}
