apiVersion: v1
kind: Secret
metadata:
  name: asylguiden-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asylguiden.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  MEILI_MASTER_KEY: {{ .Values.secret.MEILI_MASTER_KEY | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  DATABASE_USERNAME: {{ .Values.secret.POSTGRES_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  DATABASE_NAME: {{ .Values.secret.POSTGRES_DB | quote }}
  COLLECTOR_STRAPI_API_TOKEN: {{ .Values.collector.strapiApiToken | quote }}
